# example see https://github.com/github/super-linter/blob/main/TEMPLATES/.gitleaks.toml
# configuration see https://github.com/zricethezav/gitleaks#configuration

title = "gitleaks config"

useDefault = true

[allowlist]
    description = "Allowlisted files"
    paths = ['''(default_host.key)$''']
