# Dockerfile linter https://github.com/hadolint/hadolint

failure-threshold: error

ignored:
  - DL3007 # Using latest is prone to errors if the image will ever update
  - DL3018 # Pin versions in apk add
  - DL3000 # Use absolute WORKDIR
