name: Lint code

on: 
  push:
    branches-ignore: [master, main]

env:
  NODE_VERSION: 16.15

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: 👀 Checkout Code
        uses: actions/checkout@v3.0.2

      - name: ⛺️ Install Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: 📦 Install Dependencies
        run: yarn

      - name: 📚 Lint Code Base
        uses: docker://github/super-linter:v4.9.2
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          JAVASCRIPT_DEFAULT_STYLE: prettier
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: true
