name: Linter

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🛠 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📦 Install Dependencies
        run: bun install --frozen-lockfile

      - name: 📚 Lint Code Base
        run: bun run lint

      - name: 📚 Run Tests
        run: bun run test
