name: Publish packages

on:
  release:
    types: [created]

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
    - name: 👀 Checkout repo
      uses: actions/checkout@v2.3.4
    - name: 🛠 Setup Node
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@swrlab'
    - name: 📦 Install Dependencies
      run: yarn
    - name: 🚀 npm publish
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm:
    runs-on: ubuntu-latest
    steps:
    - name: 👀 Checkout repo
      uses: actions/checkout@v2.3.4
    - name: 🛠 Setup Node
      uses: actions/setup-node@v2.1.5
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@swrlab'
    - name: 📦 Install Dependencies
      run: yarn
    - name: 🚀 Github publish
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
