name: Test on Pull

on:
  workflow_dispatch:
  pull_request_target:
    types: [labeled]

env:
  NODE_VERSION: 20

jobs:
  security:
    name: Check permissions for pull request runs
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - run: |
          echo "Security checks passed!"

  test:
    needs: security
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout Code
        uses: actions/checkout@v4

      - name: 🏗 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 🛠 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📦 Install Dependencies
        run: bun install

      - name: 🧪 Run Lint
        run: bun lint

      - name: 🧪 Run Tests (in Bun)
        run: bun test

      - name: 🧪 Run Tests (in Node)
        run: npm run test
