name: Test on Push

on:
  workflow_dispatch:
  push:
    branches:
      - chore/*
      - feat/*
      - dev/*
      - main

env:
  NODE_VERSION: 18

jobs:
  test:
    name: Run Mocha Tests
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout Code
        uses: actions/checkout@v3

      - name: 🏗 Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: 📦 Install Dependencies
        run: yarn

      - name: 🧪 Run Tests
        run: yarn lint && yarn test
