name: Test on Push

on:
  workflow_dispatch:
  push:
    branches:
      - chore/*
      - feat/*
      - dev/*
      - main

env:
  NODE_VERSION: 20

jobs:
  test:
    name: Run Mocha Tests
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout Code
        uses: actions/checkout@v4

      - name: 🏗 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📦 Install Yarn
        run: corepack enable && yarn set version stable

      - name: 📦 Install Dependencies
        run: yarn install

      - name: 🧪 Run Tests
        run: yarn lint && yarn test
